# Softmax

#### In probability theory, the output of the softmax function can be used to represent a categorical distribution – that is, a probability distribution over K different possible outcomes

There is one nice attribute of Softmax as compared with standard normalisation.

* It react to low stimulation (think blurry image) of your neural net with rather uniform distribution and to high stimulation (ie. large numbers, think crisp image) with probabilities close to 0 and 1.

* While standard normalisation does not care as long as the proportion are the same.

Have a look what happens when soft max has 10 times larger input, ie your neural net got a crisp image and a lot of neurones got activated

In [ ]:
import numpy as np

def softmax(x):
    """Compute softmax values for each sets of scores in x."""
    return np.exp(x) / np.sum(np.exp(x), axis=0)

def std_norm(x):
    return x/np.sum(x)

In [43]:
softmax([1,2]) #blurry image of a ferret

array([0.26894142, 0.73105858])

In [44]:
softmax([10,20]) #crisp image of a cat

array([4.53978687e-05, 9.99954602e-01])

In [45]:
std_norm([1,2]) #blurry image of a ferret

array([0.33333333, 0.66666667])

In [46]:
std_norm([10,20]) #crisp image of a cat

array([0.33333333, 0.66666667])

## why using softmax as an activation in a hidden layer is not the best idea

1. Variables independence : a lot of regularization and effort is put to keep your variables independent, uncorrelated and quite sparse. If you use softmax layer as a hidden layer - then you will keep all your nodes (hidden variables) linearly dependent which may result in many problems and poor generalization.

2. Training issues : try to imagine that to make your network working better you have to make a part of activations from your hidden layer a little bit lower. Then - automaticaly you are making rest of them to have mean activation on a higher level which might in fact increase the error and harm your training phase.

3. Mathematical issues : by creating constrains on activations of your model you decrease the expressive power of your model without any logical explaination. The strive for having all activations the same is not worth it in my opinion.

4. Batch normalization does it better : one may consider the fact that constant mean output from a network may be useful for training. But on the other hand a technique called Batch Normalization has been already proven to work better, whereas it was reported that setting softmax as activation function in hidden layer may decrease the accuracy and the speed of learning.